const loc = {
  SP_TODOS: "São Paulo (Todos) (SP)",
  RJ_TODOS: "Rio de Janeiro (Todos) (RJ)",
  HEADER_BOTAO_LOGIN: "#header-login-button",
  WEMOBI_BOTAO_LOGIN: "#button-header-login",
  USUARIO: "#input-login",
  SENHA: "#input-password",
  BOTAO_LOGIN: "#button-login",
  WEMOBI_BOTAO_LOGIN: "#button-login-confirm",

  LOADER: '[alt="loader"]',

  LINK_INFO_VIAGEM: ".header-nav-container > :nth-child(1) > :nth-child(1) > .focusable",
  URL_INFO_VIAGEM: "informacao-para-sua-viagem",
  LINK_BAGAGEM: ".aem-Grid--12 > :nth-child(4) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image",
  ASSERT_BAGAGEM_DE_MAO: "#bagagemdemao > p",
  LINK_BAGAGEM_DESPACHADA: '[href="#bagagemdespachada"] > .btn-title',
  ASSERT_BAGAGEM_DESPACHADA: '#bagagemdespachada > [style="text-align: left;"]',
  LINK_BAGAGEM_PROIBIDA: '[href="#bagagemproibida"]',
  ASSERT_BAGAGEM_PROIBIDA: "#bagagemproibida > p",
  LINK_BAGAGENS_ESPECIAIS_ESPORTIVAS: '[href="#bagagensespeciaiseesportivas"] > .btn-title',
  ASSERT_BAGAGENS_ESPECIAIS_ESPORTIVAS: "#bagagensespeciaiseesportivas > p",
  LINK_BAGAGENS_EXTRAVIADAS_DANIFICADAS: '[href="#bagagensextraviadas"] > .btn-title',
  ASSERT_BAGAGENS_EXTRAVIADAS_DANIFICADAS: "#bagagensextraviadas > p",
  LINK_OBJETOS_ESQUECIDOS_VEICULO: '[href="#objetosesquecidos"] > .btn-title',
  ASSERT_OBJETOS_ESQUECIDOS_VEICULO: "#objetosesquecidos > p",
  LINK_COBRANCA_EXCESSO_BAGAGEM: '[href="#cobranca"] > .btn-title',
  ASSERT_COBRANCA_EXCESSO_BAGAGEM: "#cobranca > p",

  LINK_EMBARQUE: ".aem-Grid--12 > :nth-child(5) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image",
  LINK_DOCUMENTACAO_EMBARQUE: '[href="#documentacaoparaembarque"] > .btn-title',
  ASSERT_DOCUMENTACAO_EMBARQUE: "#documentacaoparaembarque > p",
  LINK_EMBARQUE_MENORES: '[href="#embarqueparamenores"] > .btn-title',
  ASSERT_EMBARQUE_MENORES: "#embarqueparamenores > p",
  LINK_HORARIO_EMBARQUE: '[href="#horariodeembarque"]',
  ASSERT_HORARIO_EMBARQUE: "#horariodeembarque > p",
  LINK_TRANSPORTE_ANIMAIS: '[href="#transportedeanimais"]',
  ASSERT_TRANSPORTE_ANIMAIS: "#transportedeanimais > p",
  LINK_SEGURO_FACULTATIVO: '[href="#segurofacultativo"]',
  ASSERT_SEGURO_FACULTATIVO: "#segurofacultativo > p",
  LINK_ALTERACOES_HORARIO: '[href="#alteracoesdehorario"]',
  ASSERT_ALTERACOES_HORARIO: "#alteracoesdehorario > p",
  LINK_COMPRA_REMARCACAO: '[style="padding: 0rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--12 > :nth-child(1) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image',
  LINK_FORMAS_PAGAMENTO: '[href="#formasdepagamento"]',
  ASSERT_FORMAS_PAGAMENTO: "#formasdepagamento > p",
  LINK_REMARCACAO_TROCA: '[href="#remarcacaoetroca"]',
  ASSERT_REMARCACAO_TROCA: "#remarcacaoetroca > p",
  LINK_CANCELAMENTO_REEMBOLSO: '[href="#cancelamentoereembolso"]',
  ASSERT_CANCELAMENTO_REEMBOLSO: "#cancelamentoereembolso > p",
  LINK_REACOMODACAO: '[href="#reacomodacao"]',
  ASSERT_REACOMODACAO: "#reacomodacao > p",
  LINK_TAXAS: '[href="#taxas"]',
  ASSERT_TAXAS: "#taxas > p",
  LINK_NOSSOS_SERVICOS: ":nth-child(2) > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image",
  LINK_NOSSOS_ONIBUS: '[href="#nossosonibus"]',
  ASSERT_NOSSOS_ONIBUS: "#nossosonibus > p",
  LINK_SALAS_VIPS: '[href="#salasvips"]',
  ASSERT_SALAS_VIPS: "#salasvips > p",
  LINK_SALAS_NETS: '[href="#salasnets"]',
  ASSERT_SALAS_NETS: '[style="margin: auto auto auto auto "] > [style="padding: 2rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--phone--12 > :nth-child(1) > #salasnets > p',
  LINK_CLUBE_GIRO: '[href="#clubegiro"]',
  ASSERT_CLUBE_GIRO: '#clubegiro > [style="padding: 2rem 2rem 2rem 2rem "] > :nth-child(1) > .aem-Grid--phone--12 > :nth-child(1) > #salasnets > p',
  LINK_DESCONTOS_GRATUIDADES: ":nth-child(4) > :nth-child(2) > :nth-child(2) > :nth-child(1) > .aem-Grid--12 > .cmp > .custom-padding > .container > :nth-child(1) > .aem-Grid > .image > .cmp-image > #cmp-image-link > .cmp-image__image",
  LINK_ESTUDANTE: '[href="#estudante"]',
  ASSERT_ESTUDANTE: "#estudante > p",
  LINK_PCD: '[href="#PCD"]',
  ASSERT_PCD: "#PCD > p",
  LINK_IDOSO: '[href="#idoso"]',
  ASSERT_IDOSO: "#idoso > p",
  LINK_ID_JOVEM: '[href="#IDJovem"]',
  ASSERT_ID_JOVEM: "#IDJovem > p",

  MENSAGEM_LOGADO: ".logged-message",
  CHECK_PASSAGEIRO: "#buyer-check-1",
  BOTAO_AVANCAR: "#btn-proceed",
  NOME_PASSAGEIRO_2: "#input-name-2",
  DATA_ANIVERSARIO_PASSAGEIRO_2: "#input-birth-2",
  NOME_PASSAGEIRO_3: "#input-name-3",
  DATA_ANIVERSARIO_PASSAGEIRO_3: "#input-birth-3",
  CLICK_PASSAGEIROS: ".passenger-footer",

  BUSCAS: {
    DESTINO_IDA: "#input-departure",
    DESTINO_VOLTA: "#input-destination",
    DATA_IDA: "#input-date",
    DATA_VOLTA: "#input-date-return",
    BOTAO_PASSAGEIROS: "#input-passengers",
    BOTAO_ADICIONAR_PASSAGEIRO: "#passenger-quantity-plus-one > .plusone",
    BOTAO_ADICIONAR_PASSAGEIRO_CRIANCA: "#infant-quantity-plus-one > .plusone",
    BOTAO_FECHAR_QUANTIDADE_PASSAGEIROS: "#close-person-quantity",
    BOTAO_BUSCAR: "#search-button",
  },
};

export default loc;
