name: Run Robot Framework Tests

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 17 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM group permissions
        run: |
          sudo chmod 666 /dev/kvm

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        env:
          LOGIN: ${{ secrets.LOGIN }}
          SENHA: ${{ secrets.SENHA }}
          LOGIN2: ${{ secrets.LOGIN2 }}
          SENHA2: ${{ secrets.SENHA2 }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASS: ${{ secrets.GMAIL_APP_PASS }}
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REMETENTE_APP: ${{ secrets.REMETENTE_APP }}
          WA_PHONE_ALFREDO: ${{ secrets.WA_PHONE_ALFREDO }}
          WA_PHONE_ANDERSON: ${{ secrets.WA_PHONE_ANDERSON }}
          TZ: Asia/Ho_Chi_Minh
        run: |
          echo "Instalando todos os aplicativos..."
          adb install-multiple ./app/apks/clube_giro/*.apk || true
          adb install-multiple ./app/apks/wemobi/*.apk || true
          adb install-multiple ./app/apks/cometa/*.apk || true
          adb install-multiple ./app/apks/1001/*.apk || true
          adb install-multiple ./app/apks/catarinense/*.apk || true

          echo "Garantindo que as animações do sistema estão desligadas..."
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

          echo "Iniciando execução principal do Robot..."
          if ! robot --outputdir results --exclude skip \
              app/appGiro/giro_login.robot \
              app/appWemobi/wemobi_login.robot \
              app/app1001/1001_login.robot \
              app/appCatarinense/catarinense_login.robot \
              app/appCometa/cometa_login.robot \
              app/app1001/1001_checkout.robot \
              app/appCatarinense/catarinense_checkout.robot \
              app/appWemobi/wemobi_checkout.robot; then

              echo "Robot Framework tests failed. Rerunning failed tests..."
              if [ -f results/output.xml ]; then
                  robot --rerunfailed results/output.xml --outputdir results_rerun \
                  app/appGiro/giro_login.robot \
                  app/appWemobi/wemobi_login.robot \
                  app/app1001/1001_login.robot \
                  app/appCatarinense/catarinense_login.robot \
                  app/appCometa/cometa_login.robot \
                  app/app1001/1001_checkout.robot \
                  app/appCatarinense/catarinense_checkout.robot \
                  app/appWemobi/wemobi_checkout.robot || true

                  if [ -f results_rerun/output.xml ]; then
                      rebot --output results/output.xml --log results/log.html --report results/report.html --merge results/output.xml results_rerun/output.xml
                  else
                      echo "No output.xml file found from rerun. Skipping merge."
                  fi
              else
                  echo "No output.xml file found. Cannot rerun failed tests."
              fi
          fi

          echo "Script execution completed"
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./results
          name: robot-test-results
          retention-days: 3
